# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.3.0/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "3ebf1a7b1df03ddff8c72b5316d9ddf3f83efefb11439ca25324ce4f6b1d6b82"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    on_arm do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.3.0/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "4a3b46e3c0438aa7446cc894bc078315ce370a0ffcafd5dd66d3b42adfbe0c79"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.3.0/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
        sha256 "f7093120b616b0f6fd62981bff4eb407753d4edab7ea8deced3de2d2ca478bc7"

        def install
          bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.3.0/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
        sha256 "9f5f2421002261e8c9ff569188364381668896c6740d820b0ba5353f33d36bea"

        def install
          bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

      fz # to search for repos
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
