# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.2.1/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "60eb4162f0dafd3361384dab1d6d8c8e6d653fd1ea5957d4badb483c14508675"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    on_arm do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.2.1/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "64d8b44823298983851213b7b03c3c55068c242431ae92e95eb6ecc27ac248e5"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.2.1/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
        sha256 "9e8a1480461aa654ea97c1d4cbedaf86083cef3c23659735c7d20193effe1524"

        def install
          bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.2.1/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
        sha256 "abcea2196355fbeebd2bbbe92bea9b8d1dbbf162b93074490d18d42d88585a9e"

        def install
          bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

      fz # to search for repos
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
