# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.4.0/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "6ace280546c54785a07e672f33ed20c73258939918a9c756072f95e663c0f46c"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    on_arm do
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.4.0/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "7f0dbbd18473df5707e695cbf3b6feb1f1b97f2f5b511aed7cabeeba6267675a"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.4.0/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
        sha256 "60ef52450e6cf9ed48f5cfcf66e90ab0e9f892f05a9851ce02e5d181f9b1ca7c"

        def install
          bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.4.0/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
        sha256 "1d5378b83485d52cc037d092f94b9fe15d8a61d04a2723ce745496669af5d920"

        def install
          bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

      fz # to search for repos
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
